apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: track-a-query-ingress
  namespace: track-a-query-production
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: track-a-query-ingress-track-a-query-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - track-a-query.service.justice.gov.uk
      secretName: track-a-query-certificate
  rules:
    - host: track-a-query.service.justice.gov.uk
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: track-a-query-service
              port:
                number: 3000

