namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task report: :environment do
    require "simplecov"

    Dir.foreach("coverage") do |file_name|
      next if File.directory?(file_name)

      file = File.join("coverage", file_name)

      Zip::File.open(file) do |zip_file|
        zip_file.each do |f|
          fpath = File.join("coverage", "#{SecureRandom.hex}.json")
          zip_file.extract(f, fpath)
        end
      end

      File.delete(file)
    end

    SimpleCov.collate Dir["coverage/*"]
  end
end
