namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task report: :environment do
    require "simplecov"

    directory_loop("coverage")

    SimpleCov.collate Dir["coverage/*"]
  end
end

def directory_loop(name)
  Dir.foreach(name) do |file_name|
    file = File.join("coverage", file_name)

    if File.directory?(file)
      directory_loop(file)
    else
      Zip::File.open(file) do |zip_file|
        zip_file.each do |f|
          fpath = File.join("coverage", "#{SecureRandom.hex}.json")
          zip_file.extract(f, fpath)
        end
      end
    end

    File.delete(file)
  end
end
