version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: site_prism
    versions:
    - "> 3.1, < 4"
  - dependency-name: capybara
    versions:
    - 3.35.3
  - dependency-name: parallel_tests
    versions:
    - 3.4.0
    - 3.5.2
    - 3.6.0
    - 3.7.0
  - dependency-name: config
    versions:
    - 2.2.3
    - 3.0.0
    - 3.1.0
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
    - 6.2.1
  - dependency-name: paper_trail
    versions:
    - 11.1.0
    - 12.0.0
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.7.0
    - 1.7.2
    - 1.7.3
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
    - 3.5.1
  - dependency-name: aws-sdk
    versions:
    - 3.0.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 5.0.0
    - 5.0.1
  - dependency-name: awesome_print
    versions:
    - 1.9.2
  - dependency-name: webdrivers
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: i18n-tasks
    versions:
    - 0.9.33
    - 0.9.34
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
    - 2.17.0
  - dependency-name: activerecord-session_store
    versions:
    - 2.0.0
  - dependency-name: bullet
    versions:
    - 6.1.3
    - 6.1.4
  - dependency-name: rails
    versions:
    - 5.2.4.5
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.4
  - dependency-name: caxlsx
    versions:
    - 3.0.4
  - dependency-name: jbuilder
    versions:
    - 2.11.2
  - dependency-name: shoulda-matchers
    versions:
    - 4.5.1
  - dependency-name: yard
    versions:
    - 0.9.26
  - dependency-name: better_errors
    versions:
    - 2.8.3
    - 2.9.1
  - dependency-name: binding_of_caller
    versions:
    - 1.0.0
  - dependency-name: mechanize
    versions:
    - 2.7.7
  - dependency-name: nokogiri
    versions:
    - 1.11.0
  - dependency-name: puma
    versions:
    - 5.1.1
  - dependency-name: pg_search
    versions:
    - 2.3.5
  - dependency-name: guard-rubocop
    versions:
    - 1.4.0
  - dependency-name: recursive-open-struct
    versions:
    - 1.1.3
  - dependency-name: rubocop-rspec
    versions:
    - 1.44.1
