inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

RSpec/VerifiedDoubles:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/ClassVars:
  Enabled: false
RSpec/RepeatedExampleGroupDescription:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/Debugger:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
Capybara/VisibilityMatcher:
  Enabled: false
RSpec/DescribeSymbol:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/FileName:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
RSpec/RepeatedDescription:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
RSpec/OverwritingSetup:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
RSpec/RepeatedExampleGroupBody:
  Enabled: false
RSpec/IteratedExpectation:
  Enabled: false
RSpec/MissingExampleGroupArgument:
  Enabled: false
Style/DateTime:
  Enabled: false
RSpec/MultipleDescribes:
  Enabled: false
RSpec/ExpectActual:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
RSpec/VoidExpect:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
# **************************************************************
# TRY NOT TO ADD OVERRIDES IN THIS FILE
#
# This repo is configured to follow the RuboCop GOV.UK styleguide.
# Any rules you override here will cause this repo to diverge from
# the way we write code in all other GOV.UK repos.
#
# See https://github.com/alphagov/rubocop-govuk/blob/main/CONTRIBUTING.md
# **************************************************************
