FROM ministryofjustice/ruby:2.3.0-webapp-onbuild

RUN touch /etc/inittab

RUN apt-get update && \
    apt-get install -y less && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && rm -fr *Release* *Sources* *Packages* && \
    truncate -s 0 /var/log/*log

ENTRYPOINT ["./run-reports.sh"]
