apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: track-a-query
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: track-a-query
    spec:
      containers:
      - name: webapp
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/correspondence/track-a-query-ecr:latest
        ports:
        - containerPort: 3000
        command: ["./run.sh"]
        env:
          - name: ENV
            value: 'dev'
          - name: RAILS_ENV
            value: 'development'
          - name: PROJECT
            value: 'correspondence-staff'
          - name: GA_TRACKING_ID
            value: 'UA-37377084-57'
          - name: SETTINGS__CTS_EMAIL_URL
            value: 'https://dev.track-a-query.service.justice.gov.uk'
          - name: SETTINGS__GOVUK_NOTIFY_API_KEY
            value: 'trackaquery_development-ec94811d-117a-4f52-8d3a-e4272089dc32-668470b3-793d-4d4f-9d6b-eb2c7a493474'
          - name: SETTINGS__SMOKE_TESTS__USERNAME
            value: 'correspondence-staff-dev+smoke.tests@digital.justice.gov.uk'
          - name: SETTINGS__SMOKE_TESTS__PASSWORD
            value: 'Go239@4jB9TbS3k$ZgDmQI!X8eW0R72^'
          - name: SECRET_KEY_BASE
            value: '40215e76a58b9b00a8a1cdc137d5b65a52b0228339d4172bf536a778a299be04f9c6a4fc0091d8bdd0d8a239855e6f7207ae0dc86cebf5cc15ae43d5ceb1c5ce'
          - name: SENTRY_DSN
            value: 'https://990ef5ad1d4143259d6a2e30d6857f72:eca2b64875a14701a4e77e1ec2608e69@sentry.service.dsd.io/97'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: url
          - name: CORRESPONDENCE_PLATFORM_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: database_password
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-elasticache-redis-output
                key: url
          - name: REDIS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: track-a-query-elasticache-redis-output
                key: auth_token
          - name: SETTINGS__CASE_UPLOADS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: bucket_name
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: secret_access_key
      - name: jobs
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/correspondence/track-a-query-ecr:latest
        command: ["./run-background-jobs.sh"]
        env:
          - name: ENV
            value: 'dev'
          - name: RAILS_ENV
            value: 'development'
          - name: PROJECT
            value: 'correspondence-staff-jobs'
          - name: GA_TRACKING_ID
            value: 'UA-37377084-57'
          - name: SETTINGS__CTS_EMAIL_URL
            value: 'https://dev.track-a-query.service.justice.gov.uk'
          - name: SETTINGS__GOVUK_NOTIFY_API_KEY
            value: 'trackaquery_development-ec94811d-117a-4f52-8d3a-e4272089dc32-668470b3-793d-4d4f-9d6b-eb2c7a493474'
          - name: SETTINGS__SMOKE_TESTS__USERNAME
            value: 'correspondence-staff-dev+smoke.tests@digital.justice.gov.uk'
          - name: SETTINGS__SMOKE_TESTS__PASSWORD
            value: 'Go239@4jB9TbS3k$ZgDmQI!X8eW0R72^'
          - name: SECRET_KEY_BASE
            value: '40215e76a58b9b00a8a1cdc137d5b65a52b0228339d4172bf536a778a299be04f9c6a4fc0091d8bdd0d8a239855e6f7207ae0dc86cebf5cc15ae43d5ceb1c5ce'
          - name: SENTRY_DSN
            value: 'https://990ef5ad1d4143259d6a2e30d6857f72:eca2b64875a14701a4e77e1ec2608e69@sentry.service.dsd.io/97'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: url
          - name: CORRESPONDENCE_PLATFORM_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: database_password
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-elasticache-redis-output
                key: url
          - name: REDIS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: track-a-query-elasticache-redis-output
                key: auth_token
          - name: SETTINGS__CASE_UPLOADS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: bucket_name
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: secret_access_key
      - name: uploads
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/correspondence/track-a-query-ecr:latest
        command: ["./run-uploads.sh"]
        env:
          - name: ENV
            value: 'dev'
          - name: RAILS_ENV
            value: 'development'
          - name: PROJECT
            value: 'correspondence-staff-uploads'
          - name: GA_TRACKING_ID
            value: 'UA-37377084-57'
          - name: SETTINGS__CTS_EMAIL_URL
            value: 'https://dev.track-a-query.service.justice.gov.uk'
          - name: SETTINGS__GOVUK_NOTIFY_API_KEY
            value: 'trackaquery_development-ec94811d-117a-4f52-8d3a-e4272089dc32-668470b3-793d-4d4f-9d6b-eb2c7a493474'
          - name: SETTINGS__SMOKE_TESTS__USERNAME
            value: 'correspondence-staff-dev+smoke.tests@digital.justice.gov.uk'
          - name: SETTINGS__SMOKE_TESTS__PASSWORD
            value: 'Go239@4jB9TbS3k$ZgDmQI!X8eW0R72^'
          - name: SECRET_KEY_BASE
            value: '40215e76a58b9b00a8a1cdc137d5b65a52b0228339d4172bf536a778a299be04f9c6a4fc0091d8bdd0d8a239855e6f7207ae0dc86cebf5cc15ae43d5ceb1c5ce'
          - name: SENTRY_DSN
            value: 'https://990ef5ad1d4143259d6a2e30d6857f72:eca2b64875a14701a4e77e1ec2608e69@sentry.service.dsd.io/97'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: url
          - name: CORRESPONDENCE_PLATFORM_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: database_password
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-elasticache-redis-output
                key: url
          - name: REDIS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: track-a-query-elasticache-redis-output
                key: auth_token
          - name: SETTINGS__CASE_UPLOADS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: bucket_name
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: track-a-query-s3-output
                key: secret_access_key
