module Cases
  class ICOSARController < ICOController
    # this class needs to exist because of autogenerated routes
    # for correspondence_type_resources - see routes.rb#55 etc

    before_action -> { set_case(params[:id]) }, only: %i[record_sar_complaint_outcome confirm_record_sar_complaint_outcome]

    def new
      authorize case_type, :can_add_case?

      permitted_correspondence_types
      new_case_for @correspondence_type, case_type
    end

    def case_type
      Case::ICO::SAR
    end

    def record_sar_complaint_outcome
      authorize @case, :can_set_outcome?
      @case = @case.decorate
      render "/cases/ico/record_sar_complaint_outcome"
    end

    def confirm_record_sar_complaint_outcome
      authorize @case, :can_set_outcome?
      @case = @case.decorate
      @case.prepare_for_recording_outcome
      if @case.update(record_complaint_outcome_params)
        @case.respond(current_user)
        redirect_to case_path(@case)
      else
        render "/cases/ico/record_sar_complaint_outcome"
      end
    end
  end
end
