module Cases
  class ICOSARController < ICOController
    # this class needs to exist because of autogenerated routes
    # for correspondence_type_resources - see routes.rb#55 etc

    before_action -> { set_case(params[:id]) }, only: %i[confirm_record_sar_complaint_outcome require_record_sar_complaint_outcome]

    def new
      authorize case_type, :can_add_case?

      permitted_correspondence_types
      new_case_for @correspondence_type, case_type
    end

    def case_type
      Case::ICO::SAR
    end

    def confirm_record_sar_complaint_outcome
      authorize @case, :can_respond?
      params = record_complaint_outcome_params
      if @case.update(params)
        redirect_to case_path(@case)
      else
        render "/cases/ico/record_sar_complaint_outcome"
      end
    end

    def require_record_sar_complaint_outcome
      # authorize @case, :can_respond?
      @case = @case.decorate
      render "/cases/ico/record_sar_complaint_outcome"
    end
  end
end
