      standard:
        initial_state: to_be_assessed
        user_roles:

        ########################### OFFENDER SAR COMPLAINT :: STANDARD WORKFLOW :: RESPONDER ########################
          responder:
            states:
              to_be_assessed:
                mark_as_require_data_review:
                  transition_to: data_review_required
                mark_as_data_to_be_requested:
                  transition_to: data_to_be_requested
                mark_as_require_response:
                  transition_to: response_required
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                edit_case:
                assign_to_team_member:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team_and_not_assigned?
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team_and_assigned?
              data_review_required:
                mark_as_vetting_in_progress:
                  transition_to: vetting_in_progress
                mark_as_require_response:
                  transition_to: response_required
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                edit_case:
              data_to_be_requested:
                mark_as_waiting_for_data:
                  transition_to: waiting_for_data
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                edit_case:
              waiting_for_data:
                mark_as_ready_for_vetting:
                  transition_to: ready_for_vetting
                mark_as_require_response:
                  transition_to: response_required
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                preview_cover_page:
                edit_case:
              ready_for_vetting:
                mark_as_vetting_in_progress:
                  transition_to: vetting_in_progress
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
              vetting_in_progress:
                mark_as_ready_to_copy:
                  transition_to: ready_to_copy
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
              ready_to_copy:
                mark_as_require_response:
                  transition_to: response_required
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                edit_case:
              response_required:
                close:
                  transition_to: closed
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_data_received:
                add_note_to_case:
                edit_case:
              closed:
                add_note_to_case:
                send_dispatch_letter:
                edit_case:

