      standard:
        initial_state: to_be_assessed
        user_roles:

        ########################### OFFENDER SAR COMPLAINT :: STANDARD WORKFLOW :: RESPONDER ########################
          responder:
            states:
              to_be_assessed:
                mark_as_require_data_review:
                  transition_to: data_review_required
                mark_as_data_to_be_requested:
                  transition_to: data_to_be_requested
                mark_as_require_response:
                  transition_to: response_required
                add_note_to_case:
                send_acknowledgement_letter:
                preview_cover_page:
                edit_case:
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              data_review_required:
                mark_as_vetting_in_progress:
                  transition_to: vetting_in_progress
                mark_as_require_response:
                  transition_to: response_required
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              data_to_be_requested:
                mark_as_waiting_for_data:
                  transition_to: waiting_for_data
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              waiting_for_data:
                mark_as_ready_for_vetting:
                  transition_to: ready_for_vetting
                mark_as_require_response:
                  if: Workflows::Predicates#is_not_litigation_complaint?
                  transition_to: response_required
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                add_data_received:
                add_note_to_case:
                send_acknowledgement_letter:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              ready_for_vetting:
                mark_as_vetting_in_progress:
                  transition_to: vetting_in_progress
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              vetting_in_progress:
                mark_as_ready_to_copy:
                  transition_to: ready_to_copy
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              ready_to_copy:
                mark_as_require_response:
                  if: Workflows::Predicates#is_not_litigation_complaint?
                  transition_to: response_required
                mark_as_ready_to_dispatch:
                  if: Workflows::Predicates#is_litigation_complaint?
                  transition_to: ready_to_dispatch
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              ready_to_dispatch:
                mark_as_legal_proceedings_ongoing:
                  if: Workflows::Predicates#is_litigation_complaint?
                  transition_to: legal_proceedings_ongoing
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                send_dispatch_letter:
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              response_required:
                add_approval_flags_for_ico:
                  if: Workflows::Predicates#is_ico_complaint_and_no_approval_flag?
                add_complaint_appeal_outcome:
                  if: Workflows::Predicates#is_ico_complaint_and_no_appeal_outcome?
                mark_as_legal_proceedings_ongoing:
                  if: Workflows::Predicates#is_litigation_complaint?
                  transition_to: legal_proceedings_ongoing
                close:
                  if: Workflows::Predicates#is_not_litigation_complaint?
                  transition_to: closed
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                send_dispatch_letter:
                add_data_received:
                add_note_to_case:
                preview_cover_page:
                edit_case:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              legal_proceedings_ongoing:
                add_approval_flags_for_litigation:
                  if: Workflows::Predicates#is_litigation_complaint_and_no_approval_flag?
                add_complaint_outcome:
                  if: Workflows::Predicates#is_litigation_complaint_and_no_outcome?
                add_complaint_costs:
                  if: Workflows::Predicates#is_litigation_complaint_and_no_costs?
                close:
                  transition_to: closed
                add_data_received:
                add_note_to_case:
                send_dispatch_letter:
                preview_cover_page:
                edit_case:
                move_to_team_member:
                  if: Workflows::Predicates#responder_is_not_assigned?
                reassign_user:
                reset_to_initial_state:
                  transition_to: to_be_assessed
              closed:
                add_approval_flags_for_ico:
                  if: Workflows::Predicates#is_ico_complaint_and_no_approval_flag?
                add_approval_flags_for_litigation:
                  if: Workflows::Predicates#is_litigation_complaint_and_no_approval_flag?
                add_complaint_appeal_outcome:
                  if: Workflows::Predicates#is_ico_complaint_and_no_appeal_outcome?
                add_complaint_outcome:
                  if: Workflows::Predicates#is_litigation_complaint_and_no_outcome?
                add_complaint_costs:
                  if: Workflows::Predicates#is_litigation_complaint_and_no_costs?
                add_note_to_case:
                send_dispatch_letter:
                preview_cover_page:
                edit_case:
                annotate_retention_changes:
                annotate_system_retention_changes:
                reset_to_initial_state:
                  transition_to: to_be_assessed
