---
:concurrency: 2
:logfile: ./log/sidekiq-report-generator.log
:queues:
  - correspondence_tool_staff_report_generator


r003_report_definition: &r003_report_definition
  class: ReportGeneratorJob
  queue: report_generator
  args: ['R003']
  description: This job generates the R003 YTD Bunsiness unit performance report

:schedule:
  R003 YTD Business unit performance report: 
    <<: *r003_report_definition
    cron: '0 0 * * * *' # Run on the hour

development:
  :schedule:
    R003 YTD Business unit performance report:
      <<: *r003_report_definition
      every: ['2m', first_in: '0s']
