
      trigger:
        initial_state: unassigned
        user_roles:
          manager:
            states:
              unassigned:
                add_message_to_case:
                assign_responder:
                  transition_to: awaiting_responder
                  after_transition: Workflows::Hooks#assign_responder_email
                destroy_case:
                edit_case:
                flag_for_clearance:
                link_a_case:
                remove_linked_case:

              awaiting_responder:
                add_message_to_case:
                assign_to_new_team:
                  after_transition: Workflows::Hooks#assign_responder_email
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:

              drafting:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                assign_to_new_team:
                  transition_to: awaiting_responder
                  after_transition: Workflows::Hooks#assign_responder_email
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                unassign_from_user:
                  transition_to: awaiting_responder

              pending_dacu_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                remove_response:
                unassign_from_user:
                  transition_to: awaiting_responder

              awaiting_dispatch:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                remove_response:
                unassign_from_user:
                  transition_to: awaiting_responder

              responded:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                close:
                  transition_to: closed
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                remove_response:
                unassign_from_user:
                  transition_to: awaiting_responder
                record_further_action:
                  if: Workflows::Predicates#can_require_further_action_for_ico?
                require_further_action:
                  if: Workflows::Predicates#can_require_further_action_for_ico?
                  after_transition: Workflows::Hooks#notify_responder_redraft_requested
                  transition_to: drafting
                require_further_action_to_responder_team:
                  if: Workflows::Predicates#can_require_further_action_for_ico?
                  after_transition: Workflows::Hooks#assign_responder_email
                  transition_to: awaiting_responder
                require_further_action_unassigned:
                  if: Workflows::Predicates#can_require_further_action_for_ico?
                  transition_to: unassigned

              closed:
                add_message_to_case:
                assign_to_new_team:
                create_overturned:
                  if: Workflows::Predicates#can_create_new_overturned_ico?
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                remove_response:
                update_closure:

          approver:
            states:
              unassigned:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                unaccept_approver_assignment:
                  if: Case::BasePolicy#can_unaccept_approval_assignment?

              awaiting_responder:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                unaccept_approver_assignment:
                  if: Case::BasePolicy#can_unaccept_approval_assignment?

              drafting:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                unaccept_approver_assignment:
                  if: Case::BasePolicy#can_unaccept_approval_assignment?

              pending_dacu_clearance:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                approve:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  transition_to: awaiting_dispatch
                  after_transition: Workflows::Hooks#notify_responder_ready_to_send
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                unaccept_approver_assignment:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                upload_response_and_approve:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  transition_to: awaiting_dispatch
                  after_transition: Workflows::Hooks#notify_responder_ready_to_send
                upload_response_and_return_for_redraft:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  after_transition: Workflows::Hooks#notify_responder_redraft_requested
                  transition_to: drafting

              awaiting_dispatch:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                respond:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  transition_to: responded

              responded:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                link_a_case:
                remove_linked_case:

          responder:
            states:
              unassigned:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                remove_linked_case:

              awaiting_responder:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                accept_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: drafting
                reject_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: unassigned
                link_a_case:
                remove_linked_case:

              drafting:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                add_responses:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: pending_dacu_clearance
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:

              pending_dacu_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:

              awaiting_dispatch:
                 add_message_to_case:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   after_transition: Workflows::Hooks#notify_responder_message_received
                 add_responses:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                 link_a_case:
                 reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#reassign_user_email
                 remove_linked_case:
                 remove_response:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to_using: Workflows::Conditionals#remove_response_next_state

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                remove_linked_case:
