apiVersion: batch/v1
kind: Job
metadata:
  name: track-a-query-migrations
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: track-a-query
      containers:
      - name: migrations
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/correspondence/track-a-query-ecr:latest
        command: ["./config/docker/entrypoint-migrations.sh"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: url
          - name: CORRESPONDENCE_PLATFORM_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: track-a-query-rds-output
                key: database_password
        envFrom:
          - configMapRef:
              name: environment-variables
          - secretRef:
              name: app-secrets
      restartPolicy: OnFailure
