      standard:
        initial_state: unassigned
        user_roles:
          manager:
            states:
              unassigned:
                add_message_to_case:
                assign_responder:
                  transition_to: awaiting_responder
                  after_transition: Workflows::Hooks#assign_responder_email
                destroy_case:
                edit_case:
                  if: Workflows::Predicates#not_overturned?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger

              awaiting_responder:
                add_message_to_case:
                assign_to_new_team:
                  after_transition: Workflows::Hooks#assign_responder_email
                destroy_case:
                edit_case:
                  if: Workflows::Predicates#not_overturned?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger

              drafting:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                assign_to_new_team:
                  transition_to: awaiting_responder
                  after_transition: Workflows::Hooks#assign_responder_email
                destroy_case:
                edit_case:
                  if: Workflows::Predicates#not_overturned?
                extend_for_pit:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                remove_pit_extension:
                  if: Workflows::Predicates#has_pit_extension?
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: :trigger
                unassign_from_user:
                  transition_to: awaiting_responder

              awaiting_dispatch:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                  if: Workflows::Predicates#not_overturned?
                extend_for_pit:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                remove_pit_extension:
                  if: Workflows::Predicates#has_pit_extension?
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger
                unassign_from_user:
                  transition_to: awaiting_responder

              responded:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                close:
                  transition_to: closed
                destroy_case:
                edit_case:
                  if: Workflows::Predicates#not_overturned?
                link_a_case:
                remove_linked_case:
                unassign_from_user:
                  transition_to: awaiting_responder
                send_back:
                  if: Workflows::Predicates#user_is_a_manager_for_case?
                  transition_to: drafting
                  after_transition: Workflows::Hooks#notify_responder_responses_sent_back

              closed:
                add_message_to_case:
                assign_to_new_team:
                destroy_case:
                edit_case:
                  if: Workflows::Predicates#not_overturned?
                link_a_case:
                remove_linked_case:
                update_closure:
                  if: Workflows::Predicates#can_edit_closure

          approver:
            states:
              unassigned:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                  switch_workflow: trigger
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval

              awaiting_responder:
                # accept approver assignment might seem an odd event to have in
                # the standard workflow, but it is here because an approver can
                # unaccept an trigger case, switching the workflow to standard,
                # and then decide to accept it again.
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                  switch_workflow: trigger
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance?

              drafting:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                  switch_workflow: trigger
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval
                unflag_for_clearance: # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance?

              awaiting_dispatch:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:

              closed:
                add_message_to_case:
                link_a_case:
                remove_linked_case:

          responder:
            states:
              unassigned:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                remove_linked_case:

              awaiting_responder:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                accept_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: drafting
                reject_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: unassigned
                link_a_case:
                remove_linked_case:

              drafting:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                add_responses:
                  if: Workflows::Predicates#assigned_team_member_and_case_outside_escalation_period?
                  transition_to: awaiting_dispatch
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#reassign_user_email
                remove_linked_case:
                remove_response:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?

              awaiting_dispatch:
                 add_message_to_case:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   after_transition: Workflows::Hooks#notify_responder_message_received
                 add_responses:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                 link_a_case:
                 reassign_user:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   after_transition: Workflows::Hooks#reassign_user_email
                 remove_linked_case:
                 remove_response:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to_using: Workflows::Conditionals#remove_response_next_state
                 respond:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to: responded

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                link_a_case:
                remove_linked_case:
