      standard:
        initial_state: unassigned
        user_roles:
          manager:
            states:
              unassigned:
                add_message_to_case:
                assign_responder:
                  transition_to: awaiting_responder
                destroy_case:
                edit_case:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger

              awaiting_responder:
                add_message_to_case:
                assign_to_new_team:
                destroy_case:
                edit_case:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger

              drafting:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                assign_to_new_team:
                  transition_to: awaiting_responder
                destroy_case:
                edit_case:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: :trigger

              awaiting_dispatch:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger

              responded:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                close:
                  transition_to: closed
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                assign_to_new_team:
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                update_closure:
                  if: Workflows::Predicates#can_edit_closure

          approver:
            states:
              unassigned:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                  switch_workflow: trigger
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                reassign_user:
                  if: Case::BasePolicy#assignments_reassign_user?
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval

              awaiting_responder:
                # accept approver assignment might seem an odd event to have in
                # the standard workflow, but it is here because an approver can
                # unaccept an trigger case, switching the workflow to standard,
                # and then decide to accept it again.
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                  switch_workflow: trigger
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                reassign_user:
                  if: Case::BasePolicy#assignments_reassign_user?
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance?

              drafting:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                  switch_workflow: trigger
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                extend_for_pit:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                reassign_user:
                  if: Case::BasePolicy#assignments_reassign_user?
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval
                unflag_for_clearance: # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance?

              awaiting_dispatch:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                extend_for_pit:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                link_a_case:
                reassign_user:
                  if: Case::BasePolicy#assignments_reassign_user?
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                  switch_workflow: full_approval

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                extend_for_pit:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                link_a_case:
                reassign_user:
                  if: Case::BasePolicy#assignments_reassign_user?
                remove_linked_case:

              closed:
                add_message_to_case:
                link_a_case:
                remove_linked_case:

          responder:
            states:
              unassigned:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                remove_linked_case:

              awaiting_responder:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                accept_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: drafting
                reject_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: unassigned
                link_a_case:
                remove_linked_case:

              drafting:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                add_responses:
                  if: Case::BasePolicy#can_add_attachment_to_flagged_and_unflagged_cases?
                  transition_to: awaiting_dispatch
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                remove_linked_case:

              awaiting_dispatch:
                 add_message_to_case:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   after_transition: Workflows::Hooks#notify_responder_message_received
                 add_responses:
                  if: Case::BasePolicy#can_add_attachment_to_flagged_and_unflagged_cases?
                 link_a_case:
                 reassign_user:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                 remove_linked_case:
                 remove_response:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to_using: Workflows::Conditionals#remove_response_next_state
                 respond:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to: responded

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                link_a_case:
                remove_linked_case:
