
      full_approval:
        initial_state: unassigned
        user_roles:
          manager:
            states:
              unassigned:
                add_message_to_case:
                assign_responder:
                  transition_to: awaiting_responder
                destroy_case:
                edit_case:
                flag_for_clearance:
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?

              awaiting_responder:
                add_message_to_case:
                assign_to_new_team:
                  transition_to: awaiting_responder
                destroy_case:
                edit_case:
                flag_for_clearance:
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?

              drafting:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                assign_to_new_team:
                  transition_to: awaiting_responder
                destroy_case:
                edit_case:
                extend_for_pit:
                flag_for_clearance:
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?

              pending_dacu_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                extend_for_pit:
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?

              pending_press_office_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                extend_for_pit:
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?

              pending_private_office_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                extend_for_pit:
                link_a_case:
                remove_linked_case:

              awaiting_dispatch:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                destroy_case:
                edit_case:
                extend_for_pit:
                flag_for_clearance:
                  switch_workflow: trigger
                link_a_case:
                remove_linked_case:
                request_further_clearance:
                  if: Case::FOI::StandardPolicy#can_request_further_clearance?
                  switch_workflow: trigger

              responded:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                close:
                  transition_to: closed
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                assign_to_new_team:
                destroy_case:
                edit_case:
                link_a_case:
                remove_linked_case:
                update_closure:
                  if: Workflows::Predicates#can_edit_closure

          approver:
            states:
              unassigned:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                flag_for_clearance:
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?
                  switch_workflow_using: Workflows::Conditionals#unflag_for_clearance_next_workflow

              awaiting_responder:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                flag_for_clearance:
                link_a_case:
                reassign_user:
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?
                  switch_workflow_using: Workflows::Conditionals#unflag_for_clearance_next_workflow

              drafting:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                flag_for_clearance:
                link_a_case:
                reassign_user:
                remove_linked_case:
                take_on_for_approval:
                  if: Case::BasePolicy#can_take_on_for_approval?
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?
                  switch_workflow_using: Workflows::Conditionals#unflag_for_clearance_next_workflow

              pending_dacu_clearance:
                accept_approver_assignment:
                  if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                approve:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  transition_to: pending_press_office_clearance
                approve_and_bypass:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  transition_to: awaiting_dispatch
                link_a_case:
                reassign_user:
                remove_linked_case:
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?
                upload_response_and_approve:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  transition_to: pending_press_office_clearance
                upload_response_approve_and_bypass:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  transition_to: awaiting_dispatch
                upload_response_and_return_for_redraft:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                  after_transition: Workflows::Hooks#notify_responder_redraft_requested
                  transition_to: drafting

              pending_press_office_clearance:
                # accept_approver_assignment:
                #   if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                approve:
                  if: Workflows::Predicates#user_is_assigned_press_officer?
                  transition_to: pending_private_office_clearance
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:
                request_amends:
                  if: Workflows::Predicates#user_is_assigned_press_officer?
                  transition_to: pending_dacu_clearance
                execute_request_amends:
                  if: Workflows::Predicates#user_is_assigned_press_officer?
                  transition_to: pending_dacu_clearance
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?

              pending_private_office_clearance:
                # accept_approver_assignment:
                #   if: Case::BasePolicy#can_accept_or_reject_approver_assignment?
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                approve:
                  if: Workflows::Predicates#user_is_assigned_private_officer?
                  transition_to: awaiting_dispatch
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:
                request_amends:
                  if: Workflows::Predicates#user_is_assigned_private_officer?
                  transition_to: pending_dacu_clearance
                execute_request_amends:
                  if: Workflows::Predicates#user_is_assigned_private_officer?
                  transition_to: pending_dacu_clearance
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?

              awaiting_dispatch:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_approver_on_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                add_responses:
                  if: Case::BasePolicy#can_add_attachment_to_flagged_and_unflagged_cases?
                flag_for_clearance:
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:
                remove_response:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to_using: Workflows::Conditionals#remove_response_next_state
                unaccept_approver_assignment:
                  if: Case::BasePolicy#can_unaccept_approval_assignment?
                unflag_for_clearance:               # needed for press/private office to unaccept
                  if: Workflows::Predicates#case_can_be_unflagged_for_clearance_by_press_or_private?
                  switch_workflow_using: Workflows::Conditionals#unflag_for_clearance_next_workflow

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#user_is_in_approving_team_for_case?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                extend_for_pit:
                  if: Workflows::Predicates#user_is_assigned_disclosure_specialist?
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                link_a_case:
                remove_linked_case:

          responder:
            states:
              unassigned:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                remove_linked_case:

              awaiting_responder:
                accept_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: drafting
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                remove_linked_case:
                reject_responder_assignment:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  transition_to: unassigned

              drafting:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                add_response_to_flagged_case:
                  if: Case::BasePolicy#can_add_attachment_to_flagged_and_unflagged_cases?
                  transition_to: pending_dacu_clearance
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                remove_linked_case:
                upload_responses:

              pending_dacu_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:

              pending_press_office_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:

              pending_private_office_clearance:
                add_message_to_case:
                  after_transition: Workflows::Hooks#notify_responder_message_received
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                link_a_case:
                reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                remove_linked_case:

              awaiting_dispatch:
                 add_message_to_case:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   after_transition: Workflows::Hooks#notify_responder_message_received
                 add_responses:
                  if: Case::BasePolicy#can_add_attachment_to_flagged_and_unflagged_cases?
                 link_a_case:
                 reassign_user:
                  if: Workflows::Predicates#case_is_assigned_to_responder_or_approver_in_same_team_as_current_user
                 remove_linked_case:
                 remove_response:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to_using: Workflows::Conditionals#remove_response_next_state
                 respond:
                   if: Workflows::Predicates#responder_is_member_of_assigned_team?
                   transition_to: responded

              responded:
                add_message_to_case:
                  if: Workflows::Predicates#responder_is_member_of_assigned_team?
                  after_transition: Workflows::Hooks#notify_responder_message_received
                link_a_case:
                remove_linked_case:

              closed:
                add_message_to_case:
                link_a_case:
                remove_linked_case:
