apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  GA_TRACKING_ID: VUEtMzczNzcwODQtNTc=
  SETTINGS__CTS_EMAIL_URL: aHR0cHM6Ly9zdGFnaW5nLnRyYWNrLWEtcXVlcnkuc2VydmljZS5qdXN0aWNlLmdvdi51aw==
  SETTINGS__GOVUK_NOTIFY_API_KEY: dHJhY2thcXVlcnlfc3RhZ2luZy1lYzk0ODExZC0xMTdhLTRmNTItOGQzYS1lNDI3MjA4OWRjMzItNjY4NDcwYjMtNzkzZC00ZDRmLTlkNmItZWIyYzdhNDkzNDc0
  SETTINGS__SMOKE_TESTS__USERNAME: Y29ycmVzcG9uZGVuY2Utc3RhZmYtZGV2K3Ntb2tlLnRlc3RzQGRpZ2l0YWwuanVzdGljZS5nb3YudWs=
  SETTINGS__SMOKE_TESTS__PASSWORD: R28yMzlANGpCOVRiUzNrJFpnRG1RSSFYOGVXMFI3Ml4=
  SECRET_KEY_BASE: NWZlNTA0ZDU1MzgxYjkxZjI5MGMzN2M2YWQzYmFlNjg0NmZkZjBhZjg1YjljY2U3NTFmNmNkNjhhMTI3ZWQ2MjUwNTM5NjU5YmVjN2RhOGM5MDdiMDdkNTRjNjQwYWVjOGZmNmQzMDQ1NTExN2Y1ZTlmNzJjMDE5ZTIxOTNlNDc=
  SENTRY_DSN: aHR0cHM6Ly85OTBlZjVhZDFkNDE0MzI1OWQ2YTJlMzBkNjg1N2Y3MjplY2EyYjY0ODc1YTE0NzAxYTRlNzdlMWVjMjYwOGU2OUBzZW50cnkuc2VydmljZS5kc2QuaW8vOTc=
