apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-search-index
spec:
  schedule: "30 * * * 6"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: track-a-query
          containers:
          - name: jobs
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/correspondence/track-a-query-ecr:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
              - |-
                set +ex
                ./cts cases reindex --non-indexed 5000
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-rds-output
                    key: url
              - name: CORRESPONDENCE_PLATFORM_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-rds-output
                    key: database_password
              - name: REDIS_URL
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-elasticache-redis-output
                    key: url
              - name: REDIS_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-elasticache-redis-output
                    key: auth_token
              - name: SETTINGS__CASE_UPLOADS_S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-s3-output
                    key: bucket_name
            envFrom:
              - configMapRef:
                  name: environment-variables
              - secretRef:
                  name: app-secrets
          restartPolicy: OnFailure
