apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: email-status
spec:
  schedule: "0 12 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: track-a-query
          containers:
          - name: jobs
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/correspondence/track-a-query-ecr:track-a-query-latest
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - "-c"
              - "bundle exec rake 'email:update_statuses'"
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-rds-replica-output
                    key: url
              - name: REDIS_URL
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-elasticache-redis-output
                    key: url
              - name: REDIS_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-elasticache-redis-output
                    key: auth_token
              - name: SETTINGS__CASE_UPLOADS_S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: track-a-query-target-s3-output
                    key: bucket_name
            envFrom:
              - configMapRef:
                  name: environment-variables
              - secretRef:
                  name: app-secrets
          restartPolicy: OnFailure
